name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run build script
        run: cd build && ./build.sh
        env:
          GITHUB_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IS_SECURE_BUILDENVIRONMENT: ${{ secrets.IS_SECURE_BUILDENVIRONMENT }}
          NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}
